### ISSUE TITLE
npmsearch has been deprecated

### ISSUE THREAD

**Issue by RyanSiu1995** [jsonresume/resume-website#108]
The link to npmsearch inside theme.html is no longer valid.
We need to change it to https://www.npmjs.com/search?q=jsonresume-theme instead.

**Comment by thomasdavis** [comment]
@RyanSiu1995 great pickup and they have an option to order by "maintained" date 

https://www.npmjs.com/search?ranking=maintenance&q=jsonresume-theme 

Will get on this one.

**Comment by thomasdavis** [comment]
Fixed this up. Will go out in next release. Thanks again.
