### ISSUE TITLE
https://registry.jsonresume.org/ is down

### ISSUE THREAD

**Issue by Anirban20001962** [jsonresume/resume-website#112]
There is some problem. My resume is not being rendered now. This is happening to everyone. Please fix as soons as possible.

**Comment by Ranjankumar666** [comment]
I am facing the same since afternoon . Please fix it

**Comment by chrisswanda** [comment]
Confirmed not working for my profile and others.
<img width="641" alt="Screen Shot 2022-01-07 at 05 35 10" src="https://user-images.githubusercontent.com/45573533/148538497-b451d12c-78f9-4abd-a3a9-ff4c426d2a2a.png">

**Comment by Malhotra-Gaurav** [comment]
Facing the same issue from last 5 day.

**Comment by cybairfly** [comment]
Also having this issue.

**Comment by kemmel-dev** [comment]
Same. What I ended up doing was installing jsonresume and respective themes from npm locally, the process of which almost put me off of using this format for my resume. Fixing this might be of importance to bringing in new users.

**Comment by Anirban20001962** [comment]
https://registery.jsonresume.org/ is up again. I am closing this issue.

**Comment by thomasdavis** [comment]
Ahhh sorry everyone! Not sure how I missed all of these notifications. It was just a billing error which I also missed the email for. 

(If this ever happens again for anyone who stumbles upon this. Tweet me at https://twitter.com/ajaxdavis or email me at thomasalwyndavis@gmail.com)
