### ISSUE TITLE
Where can I find the json for this example on the website?

### ISSUE THREAD

**Issue by pr0letariat** [jsonresume/resume-website#35]
http://themes.jsonresume.org/theme/stackoverflow

I particularly like the 'Skills' area. I have tried installing the stackoverflow theme and using it but it doesn't achieve the same look when I export to pdf.

**Comment by jontonsoup4** [comment]
[Here you go!](https://github.com/jsonresume/resume-schema/blob/v1.0.0/examples/valid/complete.json)

**Comment by thomasdavis** [comment]
@pr0letariat Unfortunately the way PDF export is dependent on how the theme author structures the template. You will have to implement it yourself and send a pull request. Most JSON resume users don't rely to hard on PDF export.
