### ISSUE TITLE
Hack My Resume project no longer live?

### ISSUE THREAD

**Issue by brettlangdon** [jsonresume/resume-website#43]
Following the http://please.hackmyresume.com/ link brings you to a page that just says `This domain is currently not approved for CashParking.`.

**Comment by mudassir0909** [comment]
Wrong repo mate :) 

https://github.com/hacksalot/HackMyResume

**Comment by thomasdavis** [comment]
Nah I think he means the link on our home page is broken.

**Comment by brettlangdon** [comment]
Yes, the link on the site does not lead to a functioning website. So it should likely be removed.
