### ISSUE TITLE
theme/modern page lacks CSS styling.

### ISSUE THREAD

**Issue by davzzar** [jsonresume/resume-website#49]
* _Browser:_ Chrome Version 64.0.3282.119 (Official Build) (64-bit)

* _OS:_ Windows 10 64-bit

The page's styling is completely absent, screenshot attached.

![2018-02-01 19_31_41-themes jsonresume org_theme_modern](https://user-images.githubusercontent.com/7673161/35699043-c3f0480e-0786-11e8-9610-64b45b17b6b0.png)

**Comment by stp-ip** [comment]
Noted. I'm not familiar with that part of the website. But hopefully another maintainer can help sooner than later.

**Comment by Antonio-Riccelli** [comment]
Hey guys, 
Is this issue still open? 
I believe the original link to the Lumen Bootstrap theme no longer works. I've tried replacing it with the most recent one, and the page shows some styling. Do we know what the "fixed" page should look like? 
![3](https://user-images.githubusercontent.com/39813213/134772394-1101a405-d133-49eb-9fdc-5fb1524c1984.jpg)

**Comment by thomasdavis** [comment]
Yeah the theme hasn't been updated. It's on my todo list, but removed from theme page now.
