### ISSUE TITLE
registry.jsonresume.org is down

### ISSUE THREAD

**Issue by 24thsaint** [jsonresume/resume-website#50]
I'm getting Error 502: Bad gateway. Although the jsonresume.org is up, registry.jsonresume.org seems to be down.

**Comment by thezachcannon** [comment]
Same. :(

**Comment by andrecarlucci** [comment]
+1

**Comment by thomasdavis** [comment]
Working on it.

**Comment by derencel20** [comment]
also, `Kendall` theme's preview is down. I wonder why?

**Comment by davidclarke-au** [comment]
Yeah, all theme previews and the editor is down =[ 

Can we help?

**Comment by thomasdavis** [comment]
Will definitely finish the fix today. And then move towards a serverless architecture for next release.

**Comment by thomasdavis** [comment]
This has been resolved, reference https://github.com/jsonresume/registry-server/issues/98

**Comment by VaibhavP17** [comment]
This seems to be down for couple of days now. I need to fetch my resume json so that I can update the same. Is there a workaround to fetch the json if the above mentioned URL is down ?

**Comment by jonlambert** [comment]
This appears to be happening again.

**Comment by 24thsaint** [comment]
+1

Can we help?

**Comment by thomasdavis** [comment]
Working on it. Tech and billing problem -.-

**Comment by kinduff** [comment]
Need help @thomasdavis? I can give a hand

**Comment by thomasdavis** [comment]
So mainly we need a way to execute npm packages (themes) against a POST'ed resume.json. 

In the past I use to run a server (theme-server) that pulled down `jsonresume-theme-*` packages and ran them against resume.jsons. It was too hard to manage. I'm wondering if there is a way we can do it serverless.

**Comment by thomasdavis** [comment]
I will be deploying a new serverless theme server within the hour, all themes will need to be manually added to the project to deploy.

**Comment by thomasdavis** [comment]
As for the registry, I am trying to figure out some nice instructions to self host instead of publishing to a shared database.

**Comment by kinduff** [comment]
I really like that idea. I was playing with the proyect yesterday and saw a lot of flaws that the theme-server has because of how it's pulling NPM packages dynamically.

If you start a project I can help you, if not, I can start something out tonight.

**Comment by thomasdavis** [comment]
Awesome, new work can be found here https://github.com/jsonresume/registry-server/issues/105

Much simpler so far
