### ISSUE TITLE
themes.jsonresume.org - Error 502 (Bad gateway)

### ISSUE THREAD

**Issue by ffsantos92** [jsonresume/resume-website#51]
E.g. http://themes.jsonresume.org/theme/kendall

**Comment by thomasdavis** [comment]
Fixing tomorrow. And perhaps new and cheaper infrastructure.

**Comment by Albert221** [comment]
Hey @thomasdavis, is there any update on this?

**Comment by thomasdavis** [comment]
This has been resolved, reference https://github.com/jsonresume/registry-server/issues/98
