### ISSUE TITLE
The website is quite old and I believe displays stale information. 

### ISSUE THREAD

**Issue by kokanek** [jsonresume/resume-website#58]
Shall I create a PR by editing it with updated instructions?

**Comment by thomasdavis** [comment]
Yeah good idea.

I will do it now

- [ ] Broken themes
- [ ] Broken integrations

**Comment by sevillaarvin** [comment]
Hi, this might be related. When I visit the [elegant theme](http://themes.jsonresume.org/theme/elegant) I get an error response "Cannot find module underscore".
