### ISSUE TITLE
Theme pages down on site

### ISSUE THREAD

**Issue by Rahulsharma0810** [jsonresume/resume-website#61]
Hey jsonresume team!

First and foremost, great project! What an excellent idea for an open standard to make visually appealing resumes! Unfortunately I am trying to preview the themes for your tool and only coming up with 502s from Cloudflare.

example:
http://themes.jsonresume.org/theme/flat
http://registry.jsonresume.org/thomasdavis?theme=polymer

Am I the only one effected by this?
Thanks,
Rahul

**Comment by russhwalker** [comment]
Seems down to me as well. I just found this, what a great idea, too bad it seems like it's a dying project.

**Comment by alistaircom** [comment]
Same, no response from themes site.

**Comment by dreamski21** [comment]
Same problem here.

While waiting for it to be fixed, you can [check archived versions (around mid-2018) of theme pages](https://web.archive.org/web/20190430202303/https://jsonresume.org/themes/).

**Comment by thomasdavis** [comment]
They work now because of https://github.com/jsonresume/registry-server/issues/105
