### ISSUE TITLE
Resume download & theme broken

### ISSUE THREAD

**Issue by jeanpoelie** [jsonresume/resume-website#63]
When i am trying to download the default template (flat) or http://themes.jsonresume.org/theme/paper
I get a 522 error.

**Comment by gwpantazes** [comment]
21 days later after @jeanpoelie's comment, the theme links are still giving a 522.

http://themes.jsonresume.org/theme/elegant

> Error 522 Ray ID: 4a1f334f3a259d85 • 2019-01-31 21:17:08 UTC
> Connection timed out
> Error at Host: themes.jsonresume.org
> 
> What happened?
> The initial connection between Cloudflare's network and the origin web server timed out. As a result, the web page can not be displayed.
> 
> What can I do?
> If you're a visitor of this website:
> Please try again in a few minutes.
> 
> **If you're the owner of this website:**
> Contact your hosting provider letting them know your web server is not completing requests. An Error 522 means that the request was able to connect to your web server, but that the request didn't finish. **The most likely cause is that something on your server is hogging resources.** Additional troubleshooting information here.

It looks like something is wrong server side, and has been wrong for at least a few weeks...

**Comment by dreamski21** [comment]
Possible duplication of issue #61
