### ISSUE TITLE
builder site seems to be down

### ISSUE THREAD

**Issue by kpennell** [jsonresume/resume-website#65]
hey guys -
https://jsonresume.org/getting-started/ 

Doesn't seem like the builder works.

![image](https://user-images.githubusercontent.com/1060385/58119316-87421f80-7bb7-11e9-8e25-6a40fc39ac86.png)

**Comment by thomasdavis** [comment]
Thanks for the report, have removed the resume builder link as it is not longer developed.

**Comment by kpennell** [comment]
@thomasdavis Darn ok. Cool to see PRs being accepted though. Guessing this project is still under semi-active development?
