### ISSUE TITLE
Jaresume link shows "No such app"

### ISSUE THREAD

**Issue by jtreminio** [jsonresume/resume-website#67]
Clicking Jaresume link (https://jaresume.com) on Schema page (https://jsonresume.org/schema/) leads to page showing "No such app" title:

![image](https://user-images.githubusercontent.com/589398/65057540-622ca600-d938-11e9-81a4-fe64cc9e87f2.png)

**Comment by Suncatcher** [comment]
The same thing with https://resumefodder.com

**Comment by CWelshE** [comment]
Oh, I just made a PR for the latter issue at #69

**Comment by SethFalco** [comment]
Closing this issue as the link was already removed in #69. (As noted in the previous comment.)
