### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by djds23** [jsonresume/resume-website#7]
Hey jsonresume team!

First and foremost, great project! What an excellent idea for an open standard to make visually appealing resumes! Unfortunately I am trying to preview the themes for your tool and only coming up with 502s from nginx.

example:
http://themes.jsonresume.org/theme/flat
http://registry.jsonresume.org/thomasdavis?theme=polymer

Am I the only one effected by this? 
Thanks,
Dean

**Comment by gixlg** [comment]
Hi, seems that the problem has returned. 
The only difference is the error message if I try to click on any theme link I got an Error 522.
