### ISSUE TITLE
Import from LinkedIn Chrome extension dead link

### ISSUE THREAD

**Issue by NansD** [jsonresume/resume-website#73]
In the [getting started](https://jsonresume.org/getting-started/) section, the "Download here" link seems to be broken. It links to https://chrome.google.com/webstore/detail/linkedin-json-resume-expo/jcaldklkmnjfpjaboilcejindjejbklh?hl=en which returns a 404 :
![image](https://user-images.githubusercontent.com/18481465/77753871-9d680a00-702a-11ea-9bba-194bda6817e6.png)

**Comment by bokub** [comment]
Here is the code line if someone wants to fix it:
https://github.com/jsonresume/resume-website/blob/gh-pages/getting-started.html#L35
