### ISSUE TITLE
Change branding

### ISSUE THREAD

**Issue by aloisdg** [jsonresume/resume-website#74]
Are we still dev-centric?

![resume](https://cloud.githubusercontent.com/assets/3449303/12216232/f164d440-b700-11e5-84a6-65063e544504.PNG)

Should we change it for "For everybody, by developers."? It is not very catchy, but we are making it with all professions in mind. I would love a new motto for the v1.

What do you think?

**Comment by chrisdotcode** [comment]
(Closing auto-manually because after 4 years, this might no longer be relevant. If still concerns anyone, give me a holler.)
